replicasCount: 1
fullName: "ms-ipfs-revproxy"
selectorLabel: "ms-ipfs-revproxy"

service:
  port:  80

container:
    name: revproxy
    image: registry.solenopsys.org/ms-ipfs-revproxy
    pullPolicy: Always
